name: 27302_test

on: [push]

jobs:
  posel_1:
    name: Obstoj testnih skript
    runs-on: ubuntu-latest
    steps:
      - name: Uporaba Checkout na repozitoiju
        uses: actions/checkout@v4

      - shell: bash
        run: |
          touch napaka.txt 
          if [ ! -d "tests" ]; then
            echo "Napaka: Testni direktorij ne obstaja." > napaka.txt
          elif [ ! -f "tests/test.py"]; then
            echo "Napaka: Test ne obstaja." > napaka.txt
          fi

      - name: Naloži rezultate za prvi posel
        uses: actions/upload-artifact@v4
        with:
          name: stanje_napak
          path: napaka.txt
    
  posel_2:
    name: Zaženi testne skripte
    needs: posel_1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - name: Uporaba Checkout na repozitoiju
        uses: actions/checkout@v4

      - name: Preveri stanje prejšnjega posla
        uses: actions/download-artifact@v4
        with:
          name: stanje_napak
      
      - shell: bash
        run: |
          file="napaka.txt"
          if [ -f "$file" ]; then
            line_count=$(wc -l < "$file")
            if [ "$line_count" -gt 0 ]; then
              cat napaka.txt
              exit 1
            fi
          fi
      
      - name: Namesti python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version}}

      - name: Namesti knjižnice
        run: pip install numpy opencv-python pytest

      - name: Zaženi teste
        run: python tests/test.py
