name: 27302_deploy

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  REPONAME: ${{ secrets.REPO_NAME }}
on:
  workflow_run:
    workflows: ["27302_test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Uporaba Checkout na repozitoriju
        uses: actions/checkout@v4

      - name: Prijava v Docker
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Zgradi docker sliko
        run: ./zapakiraj_27303.sh

      - name: Potisni docker sliko
        run: |
          docker push "$DOCKER_USERNAME/$REPONAME:latest"
